### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by colwem** [zpm-zsh/mysql-colorize#1]
This didn't initially work for me on my Mac.  I made changes in this commit c6dc1ae1fe7e53cbf7ac2e0ddd5440cab9667848 that got it working for me.  It's not going to be compatible with linux though.  The problem is that mac's sed works differently from gnu sed so I had to install gnu sed and change the shebang.  I also changed the shebang in grcat because python3 is in a different place for me.

**Comment by grigorii-horos** [comment]
I'm sorry, but I dont have Mac, and can't test this plugin. Please fork this repo and make changes.

**Comment by grigorii-horos** [comment]
Hello. I added support for FreeBSD and Mac in the master branch.
