### ISSUE TITLE
[Mac] gsed: command not found

### ISSUE THREAD

**Issue by jiayihu** [zpm-zsh/mysql-colorize#3]
I'm having the following error:
```
/Users/jiayi/.oh-my-zsh/custom/plugins/mysql-colorize/mycat: line 7: gsed: command not found
/Users/jiayi/.oh-my-zsh/custom/plugins/mysql-colorize
```

I use `Server version: 5.7.16 Homebrew` and `MacOS 10.12.2`.

**Comment by grigorii-horos** [comment]
https://github.com/horosgrisa/mysql-colorize#if-you-use-freebsd-or-mac-please-install-gnu-sed
