### ISSUE TITLE
Not working when mysql is in an script

### ISSUE THREAD

**Issue by joseffffff** [zpm-zsh/mysql-colorize#6]
I am using the 'mysql' command in a bash script that when I run it, the mysql-colorize is not working, appears like the normal mysql-client. 

When I use it in the normal command line works fine.

**Comment by grigorii-horos** [comment]
Are you `source ` this script in yours?

**Comment by joseffffff** [comment]
Ok, I saw that this package is working with an alias. I've been searching and seems that the alias doesn't works in bash scripts (didn't know it sorry). It would be great to found a way to be able to use mysql-colorize in bash scripts, I'll try to search a way and do a PR. I guess we can close the issue.
